# Generated by Django 5.1.3 on 2024-11-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_initial'),
        ('employees_app', '0004_delete_ppeauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_proofs/'),
        ),
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick_with_note', 'Sick Leave (With Note)'), ('sick_without_note', 'Sick Leave (Without Note)'), ('family', 'Family Responsibility Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('study', 'Study Leave')], max_length=20)),
                ('allocated_days', models.PositiveIntegerField(default=0)),
                ('used_days', models.PositiveIntegerField(default=0)),
                ('allocation_cycle_start', models.DateField(blank=True, null=True)),
                ('allocation_cycle_end', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='employees_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.leaveallocation'),
        ),
    ]
