# Generated by Django 5.1.3 on 2024-11-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_rename_submitted_at_leaverequest_created_at_and_more'),
        ('employees_app', '0004_delete_ppeauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendanceauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees_app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees_app.employee', verbose_name='Employee'),
        ),
    ]
